# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build, Test & Deploy to Maven Central

on:
  push:
    tags: '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Provide Signature Key
      env:
        GPG_KEY: ${{ secrets.SIG_KEY_PRIV }}
        MVN_STS: ${{ secrets.MAVEN_SETTINGS }}
      run: |
         printf "$GPG_KEY" | base64 --decode | gpg --import --no-tty --batch --yes # import PGP private key
         printf "$MVN_STS" > ~/.m2/settings.xml # provide credentials for key and maven central
    - name: Publish package
      run: mvn clean deploy
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USER }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASS }}
